### PR TITLE
Measure and track coverage

### PR DESCRIPTION
**Pull request by hobarrera**
Measure coverage and track how it varies in PRs.

Codecov has an annoying bot that jumps around commenting on issues with some stats. This is generally undesireable. To disable it, two steps need to be taken:

* Remove it from the integrations (might not be present): https://github.com/cocagne/txdbus/settings/installations
* Add `@codecov-io` to blocked users: https://github.com/settings/blocked_users

### CODE REVIEW

**Comment by cocagne** [comment]
Good idea. I tried keeping coverage fairly high but often forgot to run trial with the coverage option. Having this done automatically will be a big help. Thanks @hobarrera

**Comment by hobarrera** [comment]
Yup. I was surprised that coverage was actually pretty high (especially considering you didn't so actively track it!).

**Comment by hobarrera** [comment]
@cocagne I don't think you followed the instructions on this PR's message. ;)

https://github.com/cocagne/txdbus/pull/42#issuecomment-306215451

**Comment by cocagne** [comment]
Yeah, I skipped blocking the codecov-io user. Fixed.

**Comment by hobarrera** [comment]
Thanks!

**Comment by hobarrera** [comment]
I think you need to grant codecov access for it to post the status checks.

Hover over the checkmark [here](https://github.com/hobarrera/txdbus/commits/master) to see what I'm talking about. That same result would also appear on PRs just next to travis.

Note: You just need to sign in and grant permissions, but you **don't** need to enable the integration. That's just the bot that posts.

**Comment by cocagne** [comment]
I'm not sure I follow. Where do I grant access for it? Add one of the
codecov IDs as a collaborator or something?

**Comment by hobarrera** [comment]
Oh, I think you mostly need to log into their website, and grant them permissions to your public repos (I honestly don't *clearly* recall since I only did this once for all my repos).

**Comment by cocagne** [comment]
Hmmm. Looks like codecov has access to txdbus, both on their side and from
GitHub. I'm not sure what's wrong.

**Pull request merged**
