### PR TITLE
Fix "Fatal" flake8 checks

### PR DESCRIPTION
**Pull request by hobarrera**
Fix style violations.

Sharing this early, mostly to avoid someone else starting work on this.

### CODE REVIEW

**Comment by exvito** [comment]
Thanks for starting this.

I'm not 100% sure on what the purpose of this PR is, but from it's name "WIP: ..." I'd say I tend to disagree with such an approach. Like I commented in #63, my opinion is that PRs should be narrow-focused and short-lived the key reasons being:

* Narrow focus: easier to review.
* Narrow focus: more commits simplify future diagnostics like git bisecting.
* Short-lived: easier for concurrent PRs to be merged, leading to less merge-conflicts.

Whether the focus of a given PR is a single module, a single kind of linter error/warning or some other "logical unit of work" is up to discussion, of course (the same would go for "commits", but I guess that's up to each commiter).

All in all, what I wanted to say is that I tend to find long-lived "work-in-progress"-like PRs to make life a little more difficult for everybody. :)

I'm happy to hear your thoughts (and anybody else's).

**Comment by hobarrera** [comment]
Yup, honestly, I entirely agree. This would work if just one person was working on a project (or if the PR was narrow-scoped, but just took long).

I'll re-purpose this one to "Fix all PEP8-fatal error", and call it ready-to-merge, if you agree.

**Comment by exvito** [comment]
> Yup, honestly, I entirely agree. This would work if just one person was working on a project (or if the PR was narrow-scoped, but just took long).
> 
> I'll re-purpose this one to "Fix all PEP8-fatal error", and call it ready-to-merge, if you agree.

A suggestion, if I may: we should use more targeted "linter directives" other than `#noqa`. Otherwise we run the risk of hiding something other than the original intent -- maybe not today, but eventually in the future.

Do you think that is feasible?

**Comment by hobarrera** [comment]
I used targeted linter directives; I only fixed the Fatal ones, but excluded the other (working on the separately). Note that `setup.cfg` still says `ignore = E,W,I,C`.

I only used two `noqa`s:

* One is in a python2-only codeblock, so that's sane.
* There's an issue for the other one (#62). I made sure there was an issue for it so we don't end up hiding anything (which is what you mentioned).

I didn't fix the `pn` issue because I honestly don't understand what that code block **should** do. :(

**Comment by exvito** [comment]
> I used targeted linter directives; I only fixed the Fatal ones, but excluded the other (working on the separately). Note that setup.cfg still says ignore = E,W,I,C.
> 
> I only used two noqas:
> 
> One is in a python2-only codeblock, so that's sane.
> There's an issue for the other one (#62). I made sure there was an issue for it so we don't end up hiding anything (which is what you mentioned).

Oh, great then! :)

> I didn't fix the pn issue because I honestly don't understand what that code block should do. :(

Sure, that would be out of context here. The comment on the code with reference to the issue is useful, though.

Let's merge then.

**Pull request merged**
