### PR TITLE
Fix sending multiple unix file descriptors

### PR DESCRIPTION
**Pull request by dlech**
This should fix the bug that is causing the build failure in #81

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Can you please add some tests for this new functionality? Thanks!

**Comment by cocagne** [comment]
Thanks for jumping on these pull requests Hugo. Once you're satisfied with the result, let me know and I'll publish a new release

**Comment by WhyNotHugo** [comment]
@cocagne np! Thanks, will do! ^^

**Comment by dlech** [comment]
> Can you please add some tests for this new functionality?

This is not really new functionality. It is fixing a race condition. I'm afraid that I don't know how to write a test that can reliably reproduce a race condition. I was hoping that the fact that it doesn't break any tests would be good enough.

**Comment by WhyNotHugo** [comment]
Sorry for the lack of reply, I really don't have much to contribute here. If you've confirmed this reliably fixes the issue for you, it looks good enough for me; I'm not honestly into the finer details of this specific codepath.

Maybe @cocagne has better feedback?

**Comment by cocagne** [comment]
No, I tend to agree with David. Race conditions are very difficult to test
against so non-breakage is likely the best we can do.

**Comment by lindblandro** [comment]
I can verify that this pull request fixes a failing unit test `test_call_with_two_UNIX_FD_args`.

**Pull request closed without merging**
